# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    types:
      - opened
      - edited
    branches: 
      - main
      - 'dev/*' # Pull requests to development branches, 
      - 'feat/**' # Pull requests to feature branches, ** is that can have multiple levels of subdirectories
      - 'dev-*' # pull requests to branches that start with dev-
    

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [18.x, 20.x, 22.x]
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: execute tests
      run: npm test
    - name: lint
      run: npm run lint
    - name: publish the js file name
      run: find dist/assets/*.js -type f -execdir echo "The file name is {}" \;

  # Using artifact to store the build file for deployment
  # only one artifact with the same name can be stored in the same workflow
    - name: Archive production artifact
      uses: actions/upload-artifact@v4
      with:
      #dist-files is the name of the artifact
        name: dist-files
        path: dist
        #You can add more paths to the artifact by separating them with a comma
 #We can download the artifact in the next job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download the artifact
        uses: actions/download-artifact@v4
        with:
        #dist-files is the name of the artifact
          name: dist-files

      - name: deployment
        run: |
          echo "Deploying the artifact"
          
